### ISSUE TITLE
Configs don't save / load

### ISSUE THREAD

**Issue by LatvianModder** [LatvianModder/FTBLib#8]

**Comment by callous4567** [comment]
I've got the issue at the moment; config.json is empty (FTB Utils config that is, same for all other files alongside FTBU except Badgets)

Unknown whether you do, but i'm running it on RR instead of FTB; all things work fine, and I can actually claim chunks, the only thing that I can't do is configure FTBU.

**Comment by LatvianModder** [comment]
Fixed in v1.0.17+

**Comment by callous4567** [comment]
Thanks!

**Comment by rob5251** [comment]
This is still happening for me in v1.0.17, files generate but are empty.

**Comment by rob5251** [comment]
@LatvianModder This issue is still occurring for me in version 1.0.17.1 of FTBLib & FTBUtilities

**Comment by rob5251** [comment]
Found that if I do "/edit_config ftbu" in-game I can force the config to generate for ftbu, but all other configs will still be blank.

**Comment by SirWilli** [comment]
+1

**Comment by callous4567** [comment]
I uploaded it to my server and haven't tested it yet; will do tomorrow morning and see if configs save and/or load correctly :_:

**Comment by LatvianModder** [comment]
Fixed (i hope) in FTBLib 1.0.17.2

**Comment by rob5251** [comment]
Will test now and report back

**Comment by exetico** [comment]
I'm running the server on Debian, and here the config-file isn't saved. 

But.. I'm multiple versions after where it should been fixed.
FTBUtilities-1.7.10-1.0.17.6.jar
FTBLib-1.7.10-1.0.17.6.jar
FTBTweaks-1.0.1.jar

I'm currently running a small server, with McMyAdmin as interface.
